### ISSUE TITLE
Fix babel vulnerability

### ISSUE THREAD

**Issue by vprince1** [aws-solutions-library-samples/guidance-for-electric-vehicle-battery-health-prediction-on-aws#20]
A new "critical severity" vulnerability was identified recently for `@babel/traverse`. More details are in https://github.com/advisories/GHSA-67hx-6x53-jw92. Since your repository is using this package, kindly fix it at the earliest.

**Comment by guyu-ye** [comment]
Resolved

**Comment by vprince1** [comment]
I still see some packages using the old versions. Can you kindly make sure all dependencies are updated? Thanks

![image](https://github.com/aws-solutions-library-samples/guidance-for-electric-vehicle-battery-health-prediction-on-aws/assets/11996632/02f0acd5-bb09-4891-914b-4c7f9c2ef335)

**Comment by guyu-ye** [comment]
fixed

**Comment by guyu-ye** [comment]
fixed

**Comment by vprince1** [comment]
Thanks for fixing them. I also see other references to older versions.
![image](https://github.com/aws-solutions-library-samples/guidance-for-electric-vehicle-battery-health-prediction-on-aws/assets/11996632/8988723c-4ffd-415f-81c2-94bb94748590)

**Comment by vprince1** [comment]
thanks for fixing
